### PR TITLE
Enhancement custom plugins

### PR DESCRIPTION
**Pull request by cryptix**
I think this is good to go for now.

@mmckegg has also been using this branch for patchtron.

### CODE REVIEW

**Comment by mmckegg** [comment]
I don't think there is a way to specify custom plugins from command line. It would be cool to add this before merging 😀

**Comment by soapdog** [comment]
@cryptix I've resuming playing with this and noticed that the new systray doesn't install on Windows 10 as there is no prebuilt binary. I am trying to see if I can figure out how to do it.

**Comment by cryptix** [comment]
@soapdog did you try 0.0.2 from https://github.com/ssbc/systrayhelper/releases or did it fall through the postinstall script? if its the former, can you open an issue over there with the output?

**Comment by soapdog** [comment]
@cryptix it fails the post install, there are some typos such as `x84` instead of `x64` for windows arch in the post install script. I am about to send a PR soon. I've been testing it here until I have a working solution (talking about forked-systray)

**Comment by soapdog** [comment]
This now depends on https://github.com/ssbc/forked-systray/issues/2

**Comment by cryptix** [comment]
@mmckegg I added the flag you proposed in ec2cfa2 and added a section in the readme describing the different options. Might be a bit too short..

Do we have documentation about plugins somewhere else that we could link to?

**Comment by cryptix** [comment]
I'd like to merge this soon-ish.

This PR has a lot of unrelated changes, I know. I'd still like to just merge, to be honest.

**Comment by cryptix** [comment]
ps: the travis tests _actually_ work, they just time out.

I'm not sure what to test of it. Maybe start > whoami > stop?

It might be possible to click the trayicon using xvfb but evaluating what happend sound slike a doozy but there might be tooling for this that I'm unaware of.

**Comment by cryptix** [comment]
here you see it started but stalling: https://travis-ci.org/ssbc/scuttle-shell/jobs/428324256

**Comment by cryptix** [comment]
I will merge this and make it 0.1.0, because of the added plugin feature.

**Pull request merged**
