### PR TITLE
Windows install

### PR DESCRIPTION
**Pull request by cryptix**
updates #15 

sorry the diff is quite large because of the `standard --fix` but it showed some serious errors in the `host-app.js`.

another off-topic sidenote: I stumbled over the [chrome-native-messaging](https://www.npmjs.com/package/chrome-native-messaging) module. How can it be that `Transform`s don't have error handling?!

### CODE REVIEW

**Comment by cryptix** [comment]
@soapdog I'm not sure I understand the full extend of the windows tests (test.bat) but they run on the CI now.. ;) https://ci.appveyor.com/project/cryptix/scuttle-shell/builds/19663044

**Comment by cryptix** [comment]
nice! the windows tests don't terminate yet but The show a booting sbot already!

closes #15

**Comment by cryptix** [comment]
There is an error where it tries to read the secret that isn't there yet that goes unignored: https://ci.appveyor.com/project/cryptix/scuttle-shell/builds/19665749/job/gt0l0e01r55am42e#L89

**Comment by mixmix** [comment]
Hey @cryptix @soapdog just checkin in to say that I'm not actively trying to build scuttle-shell apps on windows.
I'm here to help try things and debug if I can. You likely already know but the

**Comment by mixmix** [comment]
https://github.com/ssbc/scuttle-shell/issues/19#issuecomment-436873658

**Comment by mixmix** [comment]
I notice this branch installer systrayhelper v0.0.4 , while master installs v0.0.3
I think I've seen less errors with this branch overall

**Comment by cryptix** [comment]
okay - the check-config scripts are also in a single file now and all four share the paths defined in `platform.js` now. I squashed some of the commits and will merge this into a new release now.

This is now also a good basis to split host_app.js and its scripts and tests into a seperate repo that then depends on scuttle-shell. cc @mixmix @soapdog

**Comment by cryptix** [comment]
published as 0.1.2

**Pull request merged**
